### ISSUE TITLE
plot 9_1_1_1 not rendering, index error generated (JH only)

### ISSUE THREAD

**Issue by InterlabsOCWA** [InterlabsOCWA/CodeDocumentation#3]

**Comment by InterlabsOCWA** [comment]
@jjyh encounters this "Error in x[[idx_w]] : no such index at level 2" at section 9.2
compared versions with Yuhan -  ggplot version 3.4.2.9 seems to be the cause (Yuhan is running 3.4.2) 
Rollback by:
require(devtools)
install_version("ggplot2", version = "3.4.2", repos = "http://cran.us.r-project.org")
issue resolved

**Comment by jjyh** [comment]
ggplot version 3.4.2.9 seems to be the cause (Yuhan is running 3.4.2)
Rollback by:
require(devtools)
install_version("ggplot2", version = "3.4.2", repos = "http://cran.us.r-project.org/")
issue resolved
